### PR TITLE
Update to 1.8, Added All missing MobTypes

### PR DESCRIPTION
**Pull request by DrkMatr1984**

### CODE REVIEW

**Comment by shansen** [comment]
I never merged this PR as it's comprehensive and therefore couldn't be merged cleanly. The repo is also deleted. I'm adding this comment as there's still developers contacting me with interest in the project.

There's a lot of good ideas and work here that could be used. I tried to contact DrkMatr1984 when this was opened but didn't hear back. It's here for anyone with interest to clean and merge the parts that makes sense. Credit DrkMatr1984 in the top of the file if you use any of this in a PR.

**Comment by DrkMatr1984** [comment]
I think I might still have the source somewhere or one of the jars. Sorry for not contacting anyone sooner. I believe it worked great for 1.8, I can see if I can make a more final branch with these features that works all the way through 1.10.2.

**Comment by DrkMatr1984** [comment]
Here's a copy of the jar I created using this PR. I'll decompile and reupload the fork then in a bit. 
[EggCatcher-1.8.zip](https://github.com/shansen/EggCatcher/files/706270/EggCatcher-1.8.zip)

**Comment by shansen** [comment]
What a coincidence. I was literally just looking at this pull request as you updated. You don't need to decompile it as your commits are still available in this pull request.

**Comment by shansen** [comment]
I've pushed it all into a seperate branch just now: https://github.com/shansen/EggCatcher/tree/DrkMatr1984

**Comment by DrkMatr1984** [comment]
Oh, thanks! I'll just pull this into my fork then xD

**Comment by DrkMatr1984** [comment]
When I made this I was pretty new at developing and thought I actually probably did a really terrible job and you didn't accept the PR because of the terrible quality. Looking back at the code I actually did a pretty decent job and the performance isn't bad. I later bought MobCatcher on spigot which is why I never continued to update my fork and eventually deleted it as I only made the fork to begin with because it took you almost 2 monthes to update to 1.8 and quite a few people contacted me on Bukkit about maybe being able to update it. Later you updated EggCatcher and went a different direction than I had and I didn't feel like manually merging your commits into my fork so I deleted the fork. If you have anyone ask about this let me know and I'll try to merge in your commits as it now seems that the dev of MobCatcher is losing interest in MC and coding and this might become more relevant to me in the future.

**Comment by shansen** [comment]
I apologize for not replying back then if I didn't talk with you outside Github. I must have forgotten, or thought I had replied on Spigot or Bukkit. The 1.8 release was delayed as I was busy and the previous version of EggCatcher was forward compatible (except for the new mobs).

I was impressed with your pull request so it wasn't so much the code that was the problem, it's that it's a big pull request. It would have required a lot of work to merge. Possibly introducing a lot of new problems with other plugins. The key is to make your commits and pull requests per feature. Then it's much easier to discuss, improve and pull. (You might already know this by now :)) I couldn't use your pull request as a 1.8 update without all the other things for example.

MobCatcher is a great plugin too so if you're happy with that there's probably no need to switch back.

**Comment by DrkMatr1984** [comment]
I know MobCatcher is a great plugin, the problem is that sometimes I don't have the time to wait for him to push an update. His 1.11 update was just released about 2-3 weeks ago and 1.11 has been out since at least November(I was even behind on the update this time so not sure when it was exactly). With open source software and being java literate, I can update most plugins myself by either finding source or by decompiling, updatings, and recompiling the source myself. However, MobCatcher is not open-source and the jar is obfuscated, which makes it very inconvenient for me to wait for his updates. EggCatcher, on the other hand, just requires me to get off my ass and update it myself if you haven't gotten around to it :)
Did you even add smacking entities with the egg to catch them as a feature? If not I made put in a PR for that on your current version. The only reason I wanted that so bad was Endermen. When you throw an egg at them, they TP away, which makes it very hard to catch with throwing the egg(if not impossible due to the way Endermen are programmed... I've never actually been able to catch one with EggCatcher when you couldn't smack them with the egg)

**Comment by shansen** [comment]
I never added the smacking functionality. It's been requested a few times for endermen though. Some players found a way around this but I can't remember how.

I have a local copy of the code where I've been attempting to cancel the enderman's teleporting or removing it when it spawns back in. But I never finished it. That might be a way to go too to make it possible to throw eggs at them.

**Pull request closed without merging**
